"""SQLAlchemy ORM models for the SwarmForge Blackboard."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, String, Text, UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from database import Base


class SessionModel(Base):
    """Core pipeline session."""
    __tablename__ = "sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    raw_spec = Column(Text, nullable=False)
    status = Column(String(50), nullable=False, default="PENDING")
    iteration = Column(Integer, nullable=False, default=0)
    overall_score = Column(Float, default=0.0)
    output_dir = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    specs = relationship("SpecArtifact", back_populates="session", cascade="all, delete-orphan")
    blueprints = relationship("ArchitectureBlueprint", back_populates="session", cascade="all, delete-orphan")
    code_files = relationship("CodebaseState", back_populates="session", cascade="all, delete-orphan")
    test_results = relationship("TestResult", back_populates="session", cascade="all, delete-orphan")
    quality_scores = relationship("QualityScore", back_populates="session", cascade="all, delete-orphan")
    errors = relationship("ErrorRegistry", back_populates="session", cascade="all, delete-orphan")
    logs = relationship("AgentLog", back_populates="session", cascade="all, delete-orphan")


class SpecArtifact(Base):
    """Decomposed spec from CEO + CPO agents."""
    __tablename__ = "spec_artifacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    version = Column(Integer, nullable=False, default=1)
    goals = Column(JSONB, nullable=False)
    tech_req = Column(JSONB, nullable=False)
    constraints = Column(JSONB, nullable=False, default=list)
    feasibility = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="specs")


class ArchitectureBlueprint(Base):
    """System architecture from CTO agent."""
    __tablename__ = "architecture_blueprints"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    version = Column(Integer, nullable=False, default=1)
    tech_stack = Column(JSONB, nullable=False)
    components = Column(JSONB, nullable=False)
    api_contracts = Column(JSONB, nullable=False)
    db_schema = Column(JSONB, nullable=False)
    file_map = Column(JSONB, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="blueprints")


class CodebaseState(Base):
    """Individual source files generated by coder agents."""
    __tablename__ = "codebase_state"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    module_name = Column(String(255), nullable=False)
    file_path = Column(Text, nullable=False)
    language = Column(String(50), nullable=False)
    content = Column(Text, nullable=False)
    review_score = Column(Float, default=0.0)
    status = Column(String(50), default="DRAFT")
    comments = Column(JSONB, default=list)
    assigned_to = Column(String(100), nullable=True)
    version = Column(Integer, default=1)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    session = relationship("SessionModel", back_populates="code_files")

    __table_args__ = (
        UniqueConstraint("session_id", "file_path", name="uq_session_file"),
    )


class TestResult(Base):
    """Test run results from QA swarm."""
    __tablename__ = "test_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    test_type = Column(String(50), nullable=False)
    coverage_pct = Column(Float, nullable=True)
    tests_total = Column(Integer, nullable=True)
    tests_passed = Column(Integer, nullable=True)
    tests_failed = Column(Integer, nullable=True)
    score = Column(Float, nullable=True)
    findings = Column(JSONB, default=list)
    raw_output = Column(Text, nullable=True)
    run_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="test_results")


class QualityScore(Base):
    """Composite quality scores per gate evaluation."""
    __tablename__ = "quality_scores"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    iteration = Column(Integer, nullable=False, default=0)
    code_quality = Column(Float, default=0.0)
    test_coverage = Column(Float, default=0.0)
    security_score = Column(Float, default=0.0)
    perf_score = Column(Float, default=0.0)
    overall = Column(Float, default=0.0)
    gate_passed = Column(Boolean, default=False)
    gate_details = Column(JSONB, default=dict)
    computed_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="quality_scores")


class ErrorRegistry(Base):
    """Error log for agent failures."""
    __tablename__ = "error_registry"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    agent_id = Column(String(100), nullable=False)
    agent_type = Column(String(100), nullable=False)
    error_type = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    context = Column(JSONB, default=dict)
    retry_count = Column(Integer, default=0)
    resolved = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="errors")


class AgentLog(Base):
    """Full audit trail of agent actions."""
    __tablename__ = "agent_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    agent_id = Column(String(100), nullable=False)
    agent_type = Column(String(100), nullable=False)
    action = Column(String(100), nullable=False)
    summary = Column(Text, nullable=True)
    tokens_in = Column(Integer, default=0)
    tokens_out = Column(Integer, default=0)
    duration_ms = Column(Integer, default=0)
    model_used = Column(String(200), nullable=True)
    ts = Column(DateTime, default=datetime.utcnow)

    session = relationship("SessionModel", back_populates="logs")
